package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "detection_cc_proto",
    deps = [
        ":detection_proto",
    ],
)

proto_library(
    name = "detection_proto",
    srcs = [
        "bbox_array.proto",
    ],
)
